spring.application.name=civicsync-backend
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/civicsync
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
jwt.secret=civicSyncDemoSecretKeyChangeThisInProductionPlease123456
jwt.expiration.ms=86400000
