spring.datasource.url=${CIVICSYNC_DB_URL}
spring.datasource.username=${CIVICSYNC_DB_USER}
spring.datasource.password=${CIVICSYNC_DB_PASSWORD}
jwt.secret=${CIVICSYNC_JWT_SECRET}
spring.jpa.hibernate.ddl-auto=validate
